### ISSUE TITLE
Add shortcut to switch between conversation quickly

### ISSUE THREAD

**Issue by lai32290** [lai32290/whatsapp-web-shortcut#1]
Currently is not possible to select next and previous conversation by shortcut, the way what I'm using is double Tab to change focus and select it by arrow.

It'll be awesome if can change conversation by shortcut.

As I know, WhatsApp web is made by React.

**Comment by TheSTL** [comment]
@lai32290  
I'am working on this issue

**Comment by lai32290** [comment]
Cool! very curious about your solution

**Comment by TheSTL** [comment]
@lai32290 
For up conversation press `up`
For down conversation press `down`
PR for this Issue is [#1](https://github.com/lai32290/whatsapp-web-shortcut/pull/4)

**Comment by lai32290** [comment]
@TheSTL that's amazing!! I'm testing it then we can merge it.
