### ISSUE TITLE
Add shortcut to search message in a conversation

### ISSUE THREAD

**Issue by lai32290** [lai32290/whatsapp-web-shortcut#6]
Add a shortcut to open Search Message in conversation.
![image](https://user-images.githubusercontent.com/903193/67622157-c8d19900-f7ed-11e9-89ce-63e8e65360ca.png)

**Comment by poissoj** [comment]
I've got this :)
Which shortcuts do you want ?

**Comment by lai32290** [comment]
Hey! Thank you!
What about the `Alt + ;` and `Command + ;` ? Because they aren't set to any function yet, as I know.

**Comment by lai32290** [comment]
If you have any suggestion, please help me ok? ;)
